const types = {
  SUBMIT_TODO: 'SUBMIT_TODO',
  DELETE_TODO: 'DELETE_TODO',
  INPUT_CHANGED: 'INPUT_CHANGED',
  UNDO_DELETE: 'UNDO_DELETE',
  TOGGLE_TODO: 'TOGGLE_TODO',
  RECEIVE_TODOS: 'RECEIVE_TODOS',
};

export default types;
