const types = {
  SUBMIT_TODO_SUCCESS: 'SUBMIT_TODO_SUCCESS',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  INPUT_CHANGED: 'INPUT_CHANGED',
  UNDO_DELETE_SUCCESS: 'UNDO_DELETE_SUCCESS',
  TOGGLE_TODO_SUCCESS: 'TOGGLE_TODO_SUCCESS',
  FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
  FETCH_TODOS_REQUEST: 'FETCH_TODOS_REQUEST',
  FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
};

export default types;
